### ISSUE TITLE
agent location

### ISSUE THREAD

**Issue by ghost** [Glavo/log4j-patch#2]
where i place it ?

**Comment by Glavo** [comment]
Our most recommended solution is to update to the latest version of Log4j2, which has patched this vulnerability.

If you cannot update the Log4j, please download [log4j-patch-agent-1.0.jar](https://github.com/Glavo/log4j-patch/releases/download/1.0/log4j-patch-agent-1.0.jar), put it anywhere, and add the JVM parameter `-javaagent:<path>` (replace the `<path>` with with the actual path of the `log4j-patch-agent-1.0.jar`  you just downloaded, e.g. `-javaagent:/home/glavo/Downloads/log4j-patch-agent-1.0.jar`).
